"use client";

import { useState } from "react";
import Section from "./components/section";
import FieldSection from "./components/FieldSection";
import { Input } from "../../../shared/components/ui/input";
import { useTheme } from "../../../contexts/themeContext";
import { LuInfo } from "react-icons/lu";



const IdentitySetup = () => {
  const {theme} = useTheme()
  const [expandedSections, setExpandedSections] = useState({
    basicInfo: true,
    contactInfo: false,
    address: false,
    declaration: false,
  });

  const toggleSection = (section: keyof typeof expandedSections) => {
    setExpandedSections((prev) => ({
      ...prev,
      [section]: !prev[section],
    }));
  };

  return (
    <>
    <div className={`bg-color-stepper-${theme} rounded-[12px] p-[16px]`}>
    <div className={`flex flex-col gap-[16px] p-[16px]`}>
       <div className={`flex flex-col gap-[16px]`}>
      <label className={`block text-[18px] font-medium text-color-muted-${theme}`}>
        Identity Label
      </label>
      <Input
        placeholder="Choose any label for your identity"
        className={`w-full bg-color-inputField-${theme} border border-color-${theme} text-color-muted-${theme} placeholder-color-${theme} placeholder-opacity-70 py-[10px] px-[20px] h-[50px] text-[14px] font-normal`}
      />
    </div>

      <Section
        title="Basic Information"
        isOpen={expandedSections.basicInfo}
        onToggle={() => toggleSection("basicInfo")}
      >
         <FieldSection />
      </Section>

      <Section
        title="Contact Information"
        isOpen={expandedSections.contactInfo}
        onToggle={() => toggleSection("contactInfo")}
      >
        <FieldSection />
      </Section>

      <Section
        title="Address"
        isOpen={expandedSections.address}
        onToggle={() => toggleSection("address")}
      >
         <FieldSection />
      </Section>

      <Section
        title="Declaration"
        isOpen={expandedSections.declaration}
        onToggle={() => toggleSection("declaration")}
      >
         <FieldSection />
      </Section>


    </div>
    </div>
    <div
                      className={`bg-color-info-text-${theme} text-color-accountType-${theme} rounded-[8px] h-[59px] py-[8px] px-2 flex items-center gap-2 text-[16px]`}
                    >
                      <span className="flex items-center gap-2">
                        <LuInfo
                          className={`text-color-info-text-${theme}`}
                          size={20}
                        />
                        <p>
                          <b>Identity Label: </b>Automatically generated by Compliance using your first name, last name, and country.
                        </p>
                      </span>
                    </div>
                    </>
  );
};

export default IdentitySetup;


